fn main() {
    println!("Hello, world!");
}

// MOVER MAKE DE ELEMENT A MAKER
// AGREGAR TESTS
// AGREGAR EL CASO DE LAS LISTAS EN DETOUR
// AGREGAR SUPER BOMB
// VER SI SE PUEDE REFACTORIZAR
// AGREGAR LEER Y ESCRIBIR ARCHIVO
